apiVersion: v1
kind: Service
metadata:
  name: osdash-postgres
  labels:
    app: osdash
    component: postgres
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: osdash
    component: postgres
