apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdash-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdash-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
