apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osdash-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.osdashboard.ai
      secretName: osdash-tls-cert
  rules:
    - host: app.osdashboard.ai
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: osdash-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osdash-frontend
                port:
                  number: 80
