"""High-level OneNote operations that pair Graph with OpenAI."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Dict, List, Optional

from ...ai_layer.tools import rewrite_html, summarize_text
from ...versioning import enqueue_git_commit
from ..msgraph.client import GraphClient
from .client import OneNoteClient


class OneNoteService:
    """Encapsulate OneNote read/write flows and local mirroring."""

    def __init__(self, mirror_root: str, client: OneNoteClient | None = None):
        self.client = client or OneNoteClient(GraphClient())
        self.mirror_root = Path(mirror_root)

    def mirror_page(self, page_id: str) -> Path:
        html = self.client.get_page_html(page_id)
        mirror_path = self.mirror_root / f"page_{page_id}.html"
        mirror_path.parent.mkdir(parents=True, exist_ok=True)
        mirror_path.write_text(html, encoding="utf-8")
        return mirror_path

    def clean_page(self, page_id: str, actor: str = "AIC") -> Path:
        html = self.client.get_page_html(page_id)
        cleaned = rewrite_html(html, "Improve structure and clarity for OneNote")
        self.client.update_page_html(page_id, cleaned)
        mirror_path = self.mirror_root / f"page_{page_id}.html"
        mirror_path.parent.mkdir(parents=True, exist_ok=True)
        mirror_path.write_text(cleaned, encoding="utf-8")
        # Auto-commit the mirror
        enqueue_git_commit([str(mirror_path)], actor=actor, reason="Clean OneNote page", tag="onenote")
        return mirror_path

    def clean_section(self, section_id: str, actor: str = "AIC") -> List[str]:
        paths: List[str] = []
        for page in self.client.list_pages(section_id):
            page_id = page.get("id")
            if not page_id:
                continue
            path = self.clean_page(page_id, actor=actor)
            paths.append(str(path))
        return paths

    def summarize_page(self, page_id: str) -> Path:
        html = self.client.get_page_html(page_id)
        summary = summarize_text(html, style="concise")
        summary_path = self.mirror_root / f"page_{page_id}_summary.txt"
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        summary_path.write_text(summary, encoding="utf-8")
        return summary_path


# Backwards compatibility functions
def summarize_page(client: OneNoteClient, page_id: str, *, actor: str = "AIC") -> Dict[str, str]:
    """Fetch a page and generate a placeholder summary payload (backwards compatibility)."""
    html = client.get_page_content(page_id)
    summary = f"Summary placeholder for page {page_id} generated by {actor}."
    return {"page_id": page_id, "summary": summary, "html": html}


def clean_section(
    client: OneNoteClient,
    section_id: str,
    *,
    actor: str = "AIC",
    max_pages: Optional[int] = None,
) -> List[Dict[str, str]]:
    """Iterate through a section and produce placeholder cleanups (backwards compatibility)."""
    pages = client.list_pages(section_id)
    cleaned: List[Dict[str, str]] = []
    for page in pages[: max_pages or len(pages)]:
        page_id = page.get("id")
        if not page_id:
            continue
        html = client.get_page_content(page_id)
        updated_html = f"<!-- cleaned by {actor} -->\n{html}"
        cleaned.append({"page_id": page_id, "html": updated_html})
    return cleaned


def mirror_page_to_disk(
    client: OneNoteClient,
    page_id: str,
    mirror_root: Path,
    *,
    actor: str = "AIC",
) -> Dict[str, Path]:
    """Store a local mirror of a cloud OneNote page and auto-commit it (backwards compatibility)."""
    html = client.get_page_content(page_id)
    meta = {"page_id": page_id, "actor": actor}

    notebook_dir = mirror_root / "notebook_unknown" / "section_unknown"
    notebook_dir.mkdir(parents=True, exist_ok=True)

    html_path = notebook_dir / f"page_{page_id}.html"
    meta_path = notebook_dir / f"page_{page_id}.meta.json"

    html_path.write_text(html, encoding="utf-8")
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    enqueue_git_commit([html_path, meta_path], actor=actor, reason="Mirror OneNote page", tag="onenote")
    return {"html_path": html_path, "meta_path": meta_path}
