"""High-level OneNote workflows that combine Graph + AI + versioning.

These functions are intentionally lightweight so they can be wired into
CLI/GUI actions or daemon jobs. Actual AI prompting can be layered in via
assistant_hub.ai when ready; for now we record placeholders so flows can
be exercised without network access.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

from assistant_hub.versioning import enqueue_git_commit

from .client import OneNoteClient


def summarize_page(client: OneNoteClient, page_id: str, *, actor: str = "AIC") -> Dict[str, str]:
    """Fetch a page and generate a placeholder summary payload."""
    html = client.get_page_content(page_id)
    summary = f"Summary placeholder for page {page_id} generated by {actor}."
    return {"page_id": page_id, "summary": summary, "html": html}


def clean_section(
    client: OneNoteClient,
    section_id: str,
    *,
    actor: str = "AIC",
    max_pages: Optional[int] = None,
) -> List[Dict[str, str]]:
    """Iterate through a section and produce placeholder cleanups."""
    pages = client.list_pages(section_id)
    cleaned: List[Dict[str, str]] = []
    for page in pages[: max_pages or len(pages)]:
        page_id = page.get("id")
        if not page_id:
            continue
        html = client.get_page_content(page_id)
        updated_html = f"<!-- cleaned by {actor} -->\n{html}"
        cleaned.append({"page_id": page_id, "html": updated_html})
    return cleaned


def mirror_page_to_disk(
    client: OneNoteClient,
    page_id: str,
    mirror_root: Path,
    *,
    actor: str = "AIC",
) -> Dict[str, Path]:
    """Store a local mirror of a cloud OneNote page and auto-commit it."""
    html = client.get_page_content(page_id)
    meta = {"page_id": page_id, "actor": actor}

    notebook_dir = mirror_root / "notebook_unknown" / "section_unknown"
    notebook_dir.mkdir(parents=True, exist_ok=True)

    html_path = notebook_dir / f"page_{page_id}.html"
    meta_path = notebook_dir / f"page_{page_id}.meta.json"

    html_path.write_text(html, encoding="utf-8")
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    enqueue_git_commit([html_path, meta_path], actor=actor, reason="Mirror OneNote page", tag="onenote")
    return {"html_path": html_path, "meta_path": meta_path}
