# Audit and Governance System
from .audit_system import (
    AuditSystem,
    AuditStorage,
    ComplianceEngine,
    GitIntegration,
    AuditEvent,
    AuditEventType,
    AuditLevel,
    EventFamily,
    ComplianceFramework,
    ComplianceRule,
    ComplianceViolation,
    DataLineage,
)
from .audit_maintenance import AuditMaintenanceConfig, AuditMaintenanceRunner
from .immutable_audit_ledger import (
    ImmutableAuditLedgerModule,
    ImmutableAuditLedgerSystem,
    get_immutable_audit_ledger_module,
    InvariantTrailLogger,
    get_invariant_trail_logger,
)
from .dynamic_cybersecurity_engine import BreachState, DynamicCybersecurityEngine
from .intelligence import (
    DataCollector,
    SyncDataCollector,
    DataSource,
    ContentValidator,
    BatchValidator,
    AccessibilityChecker,
    ValidationRule,
    ValidationResult,
)
from .content import (
    ContentConfig,
    BaseContentGenerator,
    PresentationGenerator,
    ExcelDashboardGenerator,
    WordDocumentGenerator,
)
from .system import (
    SystemOperationsController,
    NetworkServiceManager,
    ServiceConfig,
    ProcessInfo,
)
from .driver_architecture import (
    BaseDriver,
    DriverCategory,
    DriverStatus,
    DriverManifest,
    DriverCapability,
    DriverExecution,
    DriverExecutionRequest,
    ExecutionPriority,
    OSDriver,
    FilesystemDriver,
    ProcessDriver,
    PackageManagerDriver,
    PipDriver,
    GitDriver,
    DriverScheduler,
    DriverRegistry,
)
from .workspaces import (
    BaseWorkspaceEngine,
    WorkspaceStatus,
    WorkspaceConfiguration,
    WorkspaceContext,
    MasterStackEngine,
    DevDevOpsEngine,
    ResearchSimulationEngine,
    WriterEngine,
    ArchiveEngine,
    CybersecurityEngine,
    BusinessFinanceEngine,
    WorkspaceRegistry,
)
from .cognitive_framework import (
    CognitiveFrameworkManager,
    CognitivePersona,
    PersonaType,
    PersonaCapability,
    PersonaStrategy,
    CognitiveDaemon,
    DaemonType,
    DaemonStatus,
    DaemonConfiguration,
    DaemonRuntime,
    DaemonBudget,
    DaemonScope,
    EchoDaemon,
    OracleDaemon,
    CriticDaemon,
    TheoreticalReasoningFramework,
    ReasoningOperator,
    ReasoningStep,
    ReasoningTrace,
    ProjectIntelligence,
)

try:  # Some security modules require optional dependencies like bcrypt
    from .security import (
        EncryptionService,
        KeyManager,
        PolicyEngine,
        GovernanceEngine,
        AuditManager,
        BillingSystem,
        SecurityMonitor,
        AuthManager,
    )

    _HAS_SECURITY = True
except ImportError:  # pragma: no cover
    _HAS_SECURITY = False

__all__ = [
    # Audit System
    "AuditSystem",
    "AuditStorage",
    "ComplianceEngine",
    "GitIntegration",
    "AuditEvent",
    "AuditEventType",
    "AuditLevel",
    "EventFamily",
    "ComplianceFramework",
    "ComplianceRule",
    "ComplianceViolation",
    "DataLineage",
    "AuditMaintenanceConfig",
    "AuditMaintenanceRunner",
    "ImmutableAuditLedgerSystem",
    "ImmutableAuditLedgerModule",
    "get_immutable_audit_ledger_module",
    "InvariantTrailLogger",
    "get_invariant_trail_logger",
    "BreachState",
    "DynamicCybersecurityEngine",
    # Intelligence
    "DataCollector",
    "SyncDataCollector",
    "DataSource",
    "ContentValidator",
    "BatchValidator",
    "AccessibilityChecker",
    "ValidationRule",
    "ValidationResult",
    # Content
    "ContentConfig",
    "BaseContentGenerator",
    "PresentationGenerator",
    "ExcelDashboardGenerator",
    "WordDocumentGenerator",
    # System
    "SystemOperationsController",
    "NetworkServiceManager",
    "ServiceConfig",
    "ProcessInfo",
    # Driver architecture
    "BaseDriver",
    "DriverCategory",
    "DriverStatus",
    "DriverManifest",
    "DriverCapability",
    "DriverExecution",
    "DriverExecutionRequest",
    "ExecutionPriority",
    "OSDriver",
    "FilesystemDriver",
    "ProcessDriver",
    "PackageManagerDriver",
    "PipDriver",
    "GitDriver",
    "DriverScheduler",
    "DriverRegistry",
    # Workspaces
    "BaseWorkspaceEngine",
    "WorkspaceStatus",
    "WorkspaceConfiguration",
    "WorkspaceContext",
    "MasterStackEngine",
    "DevDevOpsEngine",
    "ResearchSimulationEngine",
    "WriterEngine",
    "ArchiveEngine",
    "CybersecurityEngine",
    "BusinessFinanceEngine",
    "WorkspaceRegistry",
    # Cognitive framework
    "CognitiveFrameworkManager",
    "CognitivePersona",
    "PersonaType",
    "PersonaCapability",
    "PersonaStrategy",
    "CognitiveDaemon",
    "DaemonType",
    "DaemonStatus",
    "DaemonConfiguration",
    "DaemonRuntime",
    "DaemonBudget",
    "DaemonScope",
    "EchoDaemon",
    "OracleDaemon",
    "CriticDaemon",
    "TheoreticalReasoningFramework",
    "ReasoningOperator",
    "ReasoningStep",
    "ReasoningTrace",
    "ProjectIntelligence",
]

if _HAS_SECURITY:
    __all__.extend(
        [
            "EncryptionService",
            "KeyManager",
            "PolicyEngine",
            "GovernanceEngine",
            "AuditManager",
            "BillingSystem",
            "SecurityMonitor",
            "AuthManager",
        ]
    )
