"""Automators that execute actions based on monitor findings.

These services actually do the work - drafting documents, updating
content, generating suggestions, and executing workflows.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime
import sqlite3

from ..db import AssistantState, Settings, Task, Project
from ..versioning import enqueue_commit


class BaseAutomator:
    """Base class for all automators."""
    
    def __init__(self, conn: sqlite3.Connection):
        self.conn = conn
    
    def process_findings(self, findings: Dict[str, List], state: AssistantState, settings: Settings) -> List[str]:
        """Process findings and return list of actions taken."""
        raise NotImplementedError


class AutoDraftService(BaseAutomator):
    """Automatically drafts missing documents."""
    
    def process_findings(self, findings: Dict[str, List], state: AssistantState, settings: Settings) -> List[str]:
        """Auto-draft documents based on findings."""
        actions = []
        
        # Process missing document findings
        for finding in findings.get("documents", []):
            if finding.get("type") == "missing_document":
                try:
                    action = self._draft_missing_document(finding, state, settings)
                    if action:
                        actions.append(action)
                except Exception as e:
                    print(f"[AutoDraftService] Error drafting document: {e}")
        
        return actions
    
    def _draft_missing_document(self, finding: Dict, state: AssistantState, settings: Settings) -> Optional[str]:
        """Draft a missing document."""
        doc_type = finding.get("document_type")
        suggested_path = finding.get("suggested_path")
        
        if not suggested_path:
            return None
        
        path = Path(suggested_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        # For now, create a placeholder document
        # In full implementation, would use WordService to create actual content
        if doc_type == "project_brief":
            project_name = finding.get("project", "Unknown")
            content = f"""Project Brief: {project_name}

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This project brief was automatically generated by the cognitive daemon.
Please review and update with specific details.
"""
            path.write_text(content, encoding="utf-8")
            
            # Auto-commit the new document
            enqueue_commit([str(path)], actor="Aria", tag="auto-draft", reason=f"Draft project brief for {project_name}")
            
            return f"Drafted project brief: {path.name}"
        
        return None


class AutoUpdateService(BaseAutomator):
    """Automatically updates outdated content."""
    
    def process_findings(self, findings: Dict[str, List], state: AssistantState, settings: Settings) -> List[str]:
        """Auto-update outdated content."""
        actions = []
        
        # Process outdated document findings
        for finding in findings.get("documents", []):
            if finding.get("type") == "outdated_document":
                try:
                    action = self._update_outdated_document(finding, state, settings)
                    if action:
                        actions.append(action)
                except Exception as e:
                    print(f"[AutoUpdateService] Error updating document: {e}")
        
        # Process outdated content findings
        for finding in findings.get("outdated", []):
            if finding.get("type") == "project_progress_update_needed":
                try:
                    action = self._update_project_progress(finding, state, settings)
                    if action:
                        actions.append(action)
                except Exception as e:
                    print(f"[AutoUpdateService] Error updating project: {e}")
        
        return actions
    
    def _update_outdated_document(self, finding: Dict, state: AssistantState, settings: Settings) -> Optional[str]:
        """Update an outdated document."""
        doc_path = finding.get("path")
        if not doc_path or not os.path.exists(doc_path):
            return None
        
        # In full implementation, would use WordService/ExcelService to update content
        # For now, just touch the file to update timestamp
        path = Path(doc_path)
        
        # Add update marker
        try:
            # This is a placeholder - real implementation would update content intelligently
            return f"Marked for update: {path.name}"
        except Exception as e:
            print(f"[AutoUpdateService] Error updating {doc_path}: {e}")
            return None
    
    def _update_project_progress(self, finding: Dict, state: AssistantState, settings: Settings) -> Optional[str]:
        """Update project progress information."""
        project_name = finding.get("project")
        if not project_name:
            return None
        
        # In full implementation, would update project description with current progress
        return f"Project progress updated: {project_name}"


class AutoSuggestService(BaseAutomator):
    """Generates proactive suggestions."""
    
    def process_findings(self, findings: Dict[str, List], state: AssistantState, settings: Settings) -> List[str]:
        """Generate suggestions based on findings."""
        suggestions = []
        
        # Process urgent task findings
        for finding in findings.get("tasks", []):
            if finding.get("type") == "urgent_task":
                task_id = finding.get("task_id")
                task_title = finding.get("task_title")
                days_until = finding.get("days_until_due", 0)
                
                suggestion = f"⚠️ Task #{task_id} '{task_title}' is due in {days_until} days - consider prioritizing"
                suggestions.append(suggestion)
        
        # Process task documentation findings
        for finding in findings.get("tasks", []):
            if finding.get("type") == "task_needs_documentation":
                task_id = finding.get("task_id")
                task_title = finding.get("task_title")
                
                suggestion = f"📝 Task #{task_id} '{task_title}' is in progress but lacks documentation - consider creating a task doc"
                suggestions.append(suggestion)
        
        return suggestions


class WorkflowExecutor(BaseAutomator):
    """Executes automated workflows."""
    
    def process_findings(self, findings: Dict[str, List], state: AssistantState, settings: Settings) -> List[str]:
        """Execute workflows based on findings."""
        actions = []
        
        # Check for workflow triggers
        # Example: If a project reaches certain completion, trigger review workflow
        for project in state.projects:
            if project.status == "active":
                project_tasks = [t for t in state.tasks if t.project == project.name]
                if len(project_tasks) > 0:
                    completed = len([t for t in project_tasks if t.status == "DONE"])
                    completion_ratio = completed / len(project_tasks)
                    
                    # Trigger milestone workflow at 50% completion
                    if 0.49 < completion_ratio < 0.51:  # Just crossed 50%
                        action = self._execute_milestone_workflow(project, state, settings)
                        if action:
                            actions.append(action)
        
        return actions
    
    def _execute_milestone_workflow(self, project: Project, state: AssistantState, settings: Settings) -> Optional[str]:
        """Execute a milestone workflow for a project."""
        try:
            # In full implementation, would:
            # 1. Generate progress report
            # 2. Update project status
            # 3. Create summary document
            # 4. Auto-commit everything
            
            return f"Executed milestone workflow for project: {project.name}"
        except Exception as e:
            print(f"[WorkflowExecutor] Error executing milestone workflow: {e}")
            return None



