"""API routers package."""

from . import (
    ai_systems,
    analytics,
    api_connectors,
    audit,
    chat,
    dashboard,
    document_operations,
    integrations,
    intelligence,
    reasoning,
    projects,
    research,
    search,
    platform,
    templates,
    settings,
    tasks,
    terminal,
    writer,
)

__all__ = [
    "ai_systems",
    "analytics",
    "api_connectors",
    "audit",
    "chat",
    "dashboard",
    "document_operations",
    "integrations",
    "intelligence",
    "reasoning",
    "projects",
    "research",
    "search",
    "platform",
    "templates",
    "settings",
    "tasks",
    "terminal",
    "writer",
]
