"""Document templates system for generating structured documents."""

import sqlite3
import uuid
import re
from datetime import datetime
from typing import Dict, List, Optional
from dataclasses import dataclass


@dataclass
class DocumentTemplate:
    """A template for generating documents."""
    id: str
    name: str
    category: str
    content: str
    created_at: str
    updated_at: Optional[str] = None


# Default templates - Comprehensive document types with AI governance and tracking
DEFAULT_TEMPLATES = {
    # Original templates
    "project_brief": {
        "name": "Project Brief",
        "category": "briefs",
        "content": """# {project_name} - Project Brief

**Document Version:** {version} | **Created:** {created_date} | **Last Modified:** {modified_date}
**AI Oversight:** Every AI edit is tracked | **Version Control:** Git-backed lineage
**Governance:** All changes are diffed | **Audit Trail:** Complete accountability

## Executive Overview
{overview}

## Strategic Objectives
{objectives}

## Project Scope & Boundaries
{scope}

## Critical Success Factors
{success_criteria}

## Risk Assessment
{risks}

## Resource Requirements
{resources}

## Implementation Timeline
{timeline}

## Key Stakeholders
{stakeholders}

## AI Governance Notes
- **Tracking:** All AI-generated content is versioned and attributed
- **Validation:** Human oversight required for critical decisions
- **Auditability:** Complete change history maintained via Git
- **Compliance:** Regulatory requirements tracked and enforced

---

*Document ID: {document_id} | Generated by AIC Daemon Framework | {timestamp}*
"""
    },
    "meeting_notes": {
        "name": "Meeting Notes",
        "category": "meeting",
        "content": """# Meeting Notes - {meeting_title}

**Document Version:** v{version} | **Meeting Date:** {date} | **AI Processed:** {ai_processed}
**Attendees:** {attendees}
**Location:** {location}
**Facilitator:** {facilitator}

## AI Governance Header
- **Real-time transcription:** All discussions captured and timestamped
- **Action item tracking:** Automatic follow-up daemon activated
- **Decision logging:** Critical decisions flagged for governance review
- **Version control:** Meeting notes committed to Git with diff tracking

## Agenda
{agenda}

## Key Discussion Points
{discussion}

## Critical Decisions Made
{decisions}

## Action Items (AI-Monitored)
{action_items}

## Follow-up Actions
{next_steps}

## AI-Generated Insights
- **Sentiment Analysis:** {sentiment_summary}
- **Key Topics Identified:** {topics}
- **Risk Indicators:** {risk_indicators}
- **Next Meeting Suggestions:** {recommendations}

## Meeting Effectiveness Metrics
- **Goals Achieved:** {goals_met}%
- **Action Items Created:** {action_count}
- **Decision Quality Score:** {decision_quality}/10
- **Time Utilization:** {time_efficiency}%

---

*AI Audit Trail: {audit_trail} | Document ID: {document_id} | {timestamp}*
"""
    },
    "progress_report": {
        "name": "Progress Report",
        "category": "reports",
        "content": """# Progress Report - {project_name}

**Report Period:** {period} | **Report Date:** {date} | **Version:** {version}
**AI Analysis:** Comprehensive metrics and predictive insights included
**Governance Level:** {governance_level} | **Audit Status:** {audit_status}

## Executive Summary
{executive_summary}

## Key Achievements This Period
{completed_work}

## Current Work in Progress
{in_progress}

## Critical Blockers & Issues
{blockers}

## Performance Metrics
{metrics}

## AI-Generated Predictive Analytics
### Trend Analysis
{trend_analysis}

### Risk Predictions
{risk_predictions}

### Resource Optimization Recommendations
{resource_recommendations}

### Timeline Projections
{timeline_projections}

## Next Period Objectives
{next_goals}

## AI Governance & Compliance
- **Change Tracking:** All modifications logged with diff analysis
- **Quality Assurance:** AI validation of all reported metrics
- **Regulatory Compliance:** Automated compliance checking completed
- **Audit Readiness:** Full documentation trail maintained

## Stakeholder Communications
{stakeholder_updates}

---

*AI Oversight: {ai_oversight_status} | Document ID: {document_id} | Generated: {timestamp}*
"""
    },
    "proposal": {
        "name": "Business Proposal",
        "category": "proposals",
        "content": """# {proposal_title}

**Proposal Version:** {version} | **Date:** {date} | **Prepared by:** {author}
**AI Enhancement:** Comprehensive market analysis and risk assessment included
**Governance:** All assumptions validated and version controlled

## Executive Summary
{executive_summary}

## Problem Statement & Opportunity
{problem_statement}

## Proposed Solution Architecture
{solution}

## Value Proposition & Benefits
{benefits}

## Implementation Strategy
{implementation_plan}

## Financial Analysis
{financial_analysis}

## Risk Assessment & Mitigation
{risks}

## Success Metrics & KPIs
{success_metrics}

## Timeline & Milestones
{timeline}

## Resource Requirements
{resources}

## AI-Generated Market Intelligence
### Competitive Analysis
{competitive_analysis}

### Market Opportunity Assessment
{market_assessment}

### Technical Feasibility Analysis
{technical_feasibility}

### Regulatory Compliance Review
{regulatory_compliance}

## Conclusion & Recommendation
{conclusion}

## AI Governance Statement
- **Methodology:** All analysis generated using AIC reasoning framework
- **Data Sources:** Validated and version-controlled data inputs
- **Assumptions:** Documented and tracked for future validation
- **Bias Mitigation:** Multiple AI perspectives integrated
- **Human Oversight:** Critical decisions require human validation

---

*Proposal ID: {proposal_id} | AI Confidence Score: {confidence_score}% | Generated: {timestamp}*
"""
    },

    # New comprehensive templates as requested
    "compliance_report": {
        "name": "Compliance Report",
        "category": "compliance",
        "content": """# Compliance Report - {report_title}

**Report Period:** {period} | **Report Date:** {date} | **Version:** {version}
**Regulatory Framework:** {regulatory_framework} | **Compliance Officer:** {compliance_officer}
**AI Audit:** Automated compliance monitoring and gap analysis completed

## Executive Summary
{executive_summary}

## Regulatory Requirements Overview
{regulatory_overview}

## Compliance Assessment Results
{assessment_results}

## Critical Findings
{critical_findings}

## Non-Compliance Issues
{non_compliance_issues}

## Remediation Actions Required
{remediation_actions}

## AI-Generated Compliance Analytics
### Risk Heat Map
{risk_heatmap}

### Trend Analysis
{trend_analysis}

### Predictive Compliance Issues
{predictive_issues}

### Automated Monitoring Recommendations
{monitoring_recommendations}

## Compliance Metrics Dashboard
{compliance_metrics}

## Audit Trail & Evidence
{audit_trail}

## Recommendations & Next Steps
{recommendations}

## AI Governance & Validation
- **Automated Monitoring:** Continuous compliance checking active
- **Evidence Collection:** All compliance evidence automatically cataloged
- **Version Control:** Regulatory changes tracked via Git
- **Audit Readiness:** Complete documentation trail maintained

---

*Compliance Report ID: {report_id} | AI Validation Score: {validation_score}% | {timestamp}*
"""
    },
    "patient_summary": {
        "name": "Patient Summary",
        "category": "healthcare",
        "content": """# Patient Summary - {patient_name}

**Patient ID:** {patient_id} | **Date of Birth:** {dob} | **Last Updated:** {last_updated}
**Provider:** {provider} | **Version:** {version}
**AI Analysis:** Comprehensive health pattern recognition and risk assessment completed

## Patient Demographics
{demographics}

## Chief Complaint & History of Present Illness
{chief_complaint}

## Past Medical History
{past_medical_history}

## Current Medications
{current_medications}

## Allergies & Adverse Reactions
{allergies}

## Vital Signs & Physical Examination
{vital_signs}

## Diagnostic Results
{diagnostic_results}

## Treatment Plan
{treatment_plan}

## AI-Generated Health Analytics
### Risk Stratification
{risk_stratification}

### Treatment Effectiveness Prediction
{treatment_prediction}

### Medication Interaction Analysis
{medication_analysis}

### Preventive Care Recommendations
{preventive_recommendations}

## Follow-up Schedule
{follow_up_schedule}

## Care Coordination Notes
{care_coordination}

## Patient Education Provided
{patient_education}

## AI Clinical Decision Support
- **Diagnosis Confidence:** {diagnosis_confidence}%
- **Treatment Optimization:** Evidence-based recommendations applied
- **Risk Monitoring:** Continuous health pattern analysis active
- **Outcome Prediction:** Personalized prognosis modeling completed

## Privacy & Security Notes
- **HIPAA Compliance:** All data handling compliant with privacy regulations
- **Audit Trail:** Complete access and modification history maintained
- **Data Encryption:** End-to-end encryption applied to all sensitive information

---

*Medical Record ID: {record_id} | AI Clinical Validation: {clinical_validation} | {timestamp}*
"""
    },
    "risk_assessment": {
        "name": "Risk Assessment Report",
        "category": "risk",
        "content": """# Risk Assessment Report - {assessment_title}

**Assessment Date:** {date} | **Version:** {version} | **Assessor:** {assessor}
**Risk Domain:** {risk_domain} | **Criticality Level:** {criticality_level}
**AI Analysis:** Advanced risk modeling and predictive analytics applied

## Executive Summary
{executive_summary}

## Assessment Scope & Methodology
{scope_methodology}

## Risk Identification
{risk_identification}

## Risk Analysis & Evaluation
{risk_analysis}

## Risk Prioritization Matrix
{risk_prioritization}

## Critical Risk Factors
{critical_risks}

## AI-Generated Risk Intelligence
### Predictive Risk Modeling
{predictive_modeling}

### Scenario Analysis
{scenario_analysis}

### Impact Probability Assessment
{impact_probability}

### Mitigation Strategy Optimization
{mitigation_optimization}

## Risk Mitigation Strategies
{mitigation_strategies}

## Risk Monitoring Plan
{risk_monitoring}

## Residual Risk Assessment
{residual_risk}

## Recommendations
{recommendations}

## AI Risk Analysis Validation
- **Model Confidence:** {model_confidence}%
- **Data Quality Score:** {data_quality}%
- **Uncertainty Quantification:** Comprehensive uncertainty analysis completed
- **Bias Assessment:** Risk models validated for fairness and accuracy

## Governance & Accountability
- **Risk Ownership:** Clear accountability assignments established
- **Monitoring Framework:** Automated risk tracking activated
- **Escalation Protocols:** Critical risk thresholds defined and monitored
- **Audit Trail:** Complete assessment history maintained

---

*Risk Assessment ID: {assessment_id} | AI Risk Score: {ai_risk_score} | Generated: {timestamp}*
"""
    },
    "regulatory_filing": {
        "name": "Regulatory Filing Document",
        "category": "regulatory",
        "content": """# Regulatory Filing - {filing_title}

**Filing Type:** {filing_type} | **Regulatory Agency:** {agency} | **Due Date:** {due_date}
**Version:** {version} | **Prepared by:** {prepared_by} | **Legal Review:** {legal_review_status}
**AI Compliance:** Automated regulatory requirement mapping and validation completed

## Filing Overview
{filing_overview}

## Regulatory Requirements Checklist
{requirements_checklist}

## Executive Summary
{executive_summary}

## Detailed Submission Content
{submission_content}

## Supporting Documentation
{supporting_docs}

## Certification Statements
{certification_statements}

## AI-Generated Regulatory Intelligence
### Compliance Gap Analysis
{compliance_analysis}

### Regulatory Change Impact Assessment
{regulatory_impact}

### Submission Optimization Recommendations
{submission_optimization}

### Risk Mitigation Strategies
{risk_mitigation}

## Filing Validation Results
{validation_results}

## Submission Timeline
{submission_timeline}

## Post-Filing Requirements
{post_filing_requirements}

## AI Regulatory Compliance Assurance
- **Requirement Mapping:** 100% regulatory requirements identified and addressed
- **Content Validation:** Automated accuracy and completeness checking completed
- **Format Compliance:** All regulatory formatting standards met
- **Deadline Monitoring:** Automated filing deadline tracking active

## Legal & Governance Notes
- **Attorney Review:** Required legal review completed and documented
- **Audit Trail:** Complete filing preparation history maintained
- **Version Control:** All changes tracked via Git with legal approval workflow
- **Retention Requirements:** Regulatory retention schedules established

---

*Filing Reference: {filing_reference} | AI Compliance Score: {compliance_score}% | {timestamp}*
"""
    },
    "engineering_spec": {
        "name": "Engineering Specification",
        "category": "engineering",
        "content": """# Engineering Specification - {spec_title}

**Specification ID:** {spec_id} | **Version:** {version} | **Date:** {date}
**Engineering Lead:** {engineering_lead} | **Review Status:** {review_status}
**AI Analysis:** Comprehensive technical feasibility and optimization analysis completed

## Specification Overview
{spec_overview}

## Technical Requirements
{technical_requirements}

## System Architecture
{system_architecture}

## Design Specifications
{design_specs}

## Performance Requirements
{performance_requirements}

## Interface Specifications
{interface_specs}

## Testing & Validation Requirements
{testing_requirements}

## AI-Generated Technical Intelligence
### Feasibility Analysis
{feasibility_analysis}

### Performance Optimization Recommendations
{performance_optimization}

### Cost-Benefit Analysis
{cost_benefit_analysis}

### Risk Technical Assessment
{technical_risk_assessment}

## Implementation Plan
{implementation_plan}

## Quality Assurance Plan
{qa_plan}

## Maintenance & Support Requirements
{maintenance_requirements}

## AI Engineering Validation
- **Technical Feasibility:** {feasibility_score}% confidence
- **Performance Modeling:** Comprehensive simulation analysis completed
- **Design Optimization:** AI-driven optimization recommendations applied
- **Testing Coverage:** Automated test case generation completed

## Engineering Governance
- **Peer Review:** Engineering peer review completed and documented
- **Version Control:** All design changes tracked via Git
- **Change Management:** Formal change control process established
- **Documentation Standards:** Engineering documentation standards enforced

---

*Specification ID: {spec_id} | AI Technical Validation: {technical_validation} | {timestamp}*
"""
    },
    "technical_document": {
        "name": "Technical Documentation",
        "category": "technical",
        "content": """# Technical Documentation - {doc_title}

**Document ID:** {doc_id} | **Version:** {version} | **Date:** {date}
**Technical Writer:** {technical_writer} | **Review Status:** {review_status}
**AI Enhancement:** Automated content generation and technical accuracy validation completed

## Document Overview
{doc_overview}

## Technical Specifications
{technical_specs}

## System Architecture
{system_architecture}

## API Documentation
{api_docs}

## Configuration Guide
{config_guide}

## Troubleshooting Guide
{troubleshooting_guide}

## Performance Characteristics
{performance_characteristics}

## AI-Generated Technical Content
### Automated Documentation Analysis
{doc_analysis}

### Technical Accuracy Validation
{accuracy_validation}

### Content Optimization Recommendations
{content_optimization}

### Cross-Reference Analysis
{cross_reference_analysis}

## Installation Instructions
{installation_instructions}

## User Guide
{user_guide}

## Developer Guide
{developer_guide}

## Reference Materials
{reference_materials}

## AI Documentation Intelligence
- **Content Completeness:** {completeness_score}% coverage of technical requirements
- **Technical Accuracy:** Automated validation of all technical claims completed
- **User Experience:** Documentation usability analysis completed
- **Maintenance Tracking:** Automated detection of documentation drift from code

## Technical Governance
- **Technical Review:** Subject matter expert review completed
- **Version Synchronization:** Documentation synchronized with code versions
- **Change Tracking:** All technical updates logged with impact analysis
- **Quality Assurance:** Technical writing standards enforced and validated

---

*Document ID: {doc_id} | AI Content Validation: {content_validation} | {timestamp}*
"""
    },
    "product_update": {
        "name": "Product Update Announcement",
        "category": "product",
        "content": """# Product Update Announcement - {product_name} v{version}

**Release Date:** {release_date} | **Version:** {version} | **Release Type:** {release_type}
**Product Manager:** {product_manager} | **Engineering Lead:** {engineering_lead}
**AI Analysis:** Comprehensive user impact assessment and adoption prediction completed

## Release Overview
{release_overview}

## New Features & Capabilities
{new_features}

## Enhancements & Improvements
{enhancements}

## Bug Fixes & Stability Improvements
{bug_fixes}

## Breaking Changes
{breaking_changes}

## Migration Guide
{migration_guide}

## AI-Generated Product Intelligence
### User Impact Analysis
{user_impact_analysis}

### Adoption Prediction Model
{adoption_prediction}

### Competitive Positioning Update
{competitive_positioning}

### Market Opportunity Assessment
{market_opportunity}

## Technical Specifications
{technical_specs}

## System Requirements
{system_requirements}

## Installation Instructions
{installation_instructions}

## Known Issues & Limitations
{known_issues}

## Future Roadmap Preview
{future_roadmap}

## AI Product Validation
- **User Experience Impact:** {ux_impact_score}% positive user experience improvement
- **Technical Stability:** Automated testing coverage: {testing_coverage}%
- **Market Readiness:** Product positioning analysis completed
- **Adoption Optimization:** Launch strategy recommendations generated

## Product Governance
- **Quality Assurance:** Comprehensive QA testing completed and documented
- **Security Review:** Security assessment completed with no critical issues
- **Compliance Check:** All regulatory requirements validated
- **Change Management:** Formal product change approval process followed

---

*Release ID: {release_id} | AI Product Score: {product_score}/10 | {timestamp}*
"""
    },
    "operational_manual": {
        "name": "Operational Manual",
        "category": "operations",
        "content": """# Operational Manual - {manual_title}

**Manual ID:** {manual_id} | **Version:** {version} | **Effective Date:** {effective_date}
**Operations Lead:** {operations_lead} | **Review Cycle:** {review_cycle}
**AI Optimization:** Automated process optimization and efficiency analysis completed

## Manual Overview
{manual_overview}

## Operational Procedures
{operational_procedures}

## Standard Operating Procedures (SOPs)
{sops}

## Process Workflows
{process_workflows}

## Quality Control Procedures
{quality_control}

## Safety Protocols
{safety_protocols}

## Emergency Response Procedures
{emergency_procedures}

## AI-Generated Operational Intelligence
### Process Optimization Analysis
{process_optimization}

### Efficiency Benchmarking
{efficiency_benchmarking}

### Risk Assessment Matrix
{risk_assessment_matrix}

### Continuous Improvement Recommendations
{improvement_recommendations}

## Training Requirements
{training_requirements}

## Performance Metrics & KPIs
{performance_metrics}

## Monitoring & Reporting
{monitoring_reporting}

## Compliance Requirements
{compliance_requirements}

## AI Operations Validation
- **Process Efficiency:** {efficiency_score}% improvement opportunity identified
- **Quality Assurance:** Automated quality control validation completed
- **Risk Mitigation:** Comprehensive risk assessment matrix generated
- **Training Optimization:** Personalized training path recommendations created

## Operational Governance
- **Process Ownership:** Clear responsibility assignments established
- **Change Management:** Formal operational change control process active
- **Audit Compliance:** Operational audit requirements tracked and monitored
- **Continuous Improvement:** Automated process performance monitoring activated

---

*Manual ID: {manual_id} | AI Process Score: {process_score}/10 | Last Reviewed: {last_reviewed}*
"""
    },

    # Sample templates for different file formats
    "sample_csv_data": {
        "name": "CSV Data Template",
        "category": "data",
        "content": """# CSV Data Template - {dataset_name}
# Version: {version} | Created: {created_date} | AI Processed: {ai_processed}
# Data Governance: Version controlled | Audit Trail: Complete change history
# AI Tracking: Every modification logged | Compliance: Data quality validated

# Sample CSV Structure:
# id,name,value,timestamp,ai_confidence,validated_by,change_reason
# 1,Sample Data Point 1,42.5,2024-12-07T10:30:00Z,0.95,human_reviewer,data_import
# 2,Sample Data Point 2,37.8,2024-12-07T10:31:00Z,0.89,ai_validated,automated_update
# 3,Sample Data Point 3,51.2,2024-12-07T10:32:00Z,0.97,human_approved,manual_entry

# AI Governance Notes:
# - All data points include AI confidence scores
# - Validation status tracked for each entry
# - Change reasons documented for audit compliance
# - Version history maintained via Git integration
# - Automated quality checks performed on import

# Data Dictionary:
# id: Unique identifier (auto-generated)
# name: Human-readable description
# value: Numerical or categorical data
# timestamp: ISO 8601 timestamp with timezone
# ai_confidence: AI model's confidence score (0.0-1.0)
# validated_by: human_reviewer | ai_validated | human_approved | system_generated
# change_reason: Description of why this data point was added/modified

# Export this template to CSV format for actual data storage
"""
    },
    "sample_json_schema": {
        "name": "JSON Schema Template",
        "category": "data",
        "content": """{
  "schema": {
    "version": "{version}",
    "name": "{schema_name}",
    "description": "AI-governed JSON schema with complete audit trail",
    "created": "{created_date}",
    "ai_processed": "{ai_processed}",
    "governance": {
      "tracking": "Every AI edit tracked",
      "versioning": "Git-backed lineage",
      "auditing": "All changes diffed",
      "compliance": "Complete accountability"
    }
  },
  "data": {
    "id": "uuid-string",
    "name": "human-readable-name",
    "value": "numerical-or-categorical",
    "metadata": {
      "timestamp": "2024-12-07T10:30:00Z",
      "ai_confidence": 0.95,
      "validated_by": "human_reviewer|ai_validated|human_approved",
      "change_reason": "data_import|automated_update|manual_entry",
      "version_history": [
        {
          "version": "1.0",
          "timestamp": "2024-12-07T10:30:00Z",
          "changed_by": "system",
          "change_type": "creation",
          "ai_oversight": "initial_validation_completed"
        }
      ]
    },
    "ai_insights": {
      "anomaly_score": 0.02,
      "trend_prediction": "stable",
      "quality_score": 0.98,
      "recommendations": [
        "Data point within normal parameters",
        "No action required"
      ]
    }
  },
  "audit_trail": {
    "document_id": "{document_id}",
    "total_versions": 1,
    "last_modified": "{timestamp}",
    "governance_status": "compliant",
    "retention_policy": "7_years",
    "access_log": []
  }
}"""
    },
    "sample_pdf_template": {
        "name": "PDF Document Template",
        "category": "document",
        "content": """# PDF Document Template - {document_title}
# Version: {version} | Created: {created_date} | Format: PDF
# AI Processing: OCR-enabled | Governance: Full audit trail
# Compliance: Regulatory standards met | Accessibility: WCAG 2.1 AA

## Document Information
- **Title:** {document_title}
- **Author:** {author}
- **Creation Date:** {created_date}
- **Last Modified:** {modified_date}
- **Version:** {version}
- **Classification:** {classification_level}

## AI Governance Statement
This PDF document has been processed and validated by our AI governance framework:

- **Content Analysis:** Automated text extraction and semantic analysis completed
- **Compliance Check:** Regulatory requirements validated
- **Accessibility Audit:** WCAG 2.1 AA compliance verified
- **Version Control:** Complete change history maintained
- **Digital Signature:** Cryptographic integrity assurance applied

## Document Structure
1. Executive Summary
2. Main Content Sections
3. Supporting Data
4. Conclusions
5. Appendices

## Technical Specifications
- **Format:** PDF 1.7 (ISO 32000-1)
- **Compression:** Optimized for web delivery
- **Security:** Password protection applied
- **Metadata:** Complete XMP metadata included
- **OCR Layer:** Searchable text layer embedded

## AI-Generated Insights
### Content Analysis
- **Readability Score:** {readability_score}/100
- **Key Topics:** {key_topics}
- **Sentiment Analysis:** {sentiment}
- **Compliance Status:** {compliance_status}

### Optimization Recommendations
- **File Size:** {file_size_mb}MB (optimized for distribution)
- **Loading Performance:** {performance_score}/10
- **Accessibility Score:** {accessibility_score}/100

## Usage Guidelines
- This template should be used for official documents requiring PDF format
- All content must pass AI compliance validation before finalization
- Version control is mandatory for all changes
- Digital signatures required for legal documents

## Change History
| Version | Date | Changed By | Change Description | AI Validation |
|---------|------|------------|-------------------|---------------|
| {version} | {created_date} | {author} | Initial creation | ✅ Passed |

---
*Document ID: {document_id} | AI Validation: ✅ Complete | Generated: {timestamp}*
"""
    },
    "sample_excel_template": {
        "name": "Excel Workbook Template",
        "category": "spreadsheet",
        "content": """# Excel Workbook Template - {workbook_title}
# Version: {version} | Created: {created_date} | Format: XLSX
# AI Analysis: Formula validation and data integrity checks completed
# Governance: Cell-level audit trail | Automation: Macro security validated

## Workbook Structure
### Worksheets Included:
1. **Dashboard** - Executive summary with charts and KPIs
2. **Data** - Raw data with AI-generated insights
3. **Analysis** - Calculations and trend analysis
4. **Reports** - Automated report generation
5. **Audit** - Complete change history and validation logs

## AI Governance Features
- **Formula Validation:** All Excel formulas checked for accuracy and efficiency
- **Data Integrity:** Automated detection of data anomalies and inconsistencies
- **Change Tracking:** Cell-level modification history maintained
- **Security Audit:** Macro and VBA code security validated
- **Performance Optimization:** Workbook optimization recommendations applied

## Key Features
### Dashboard Sheet
- Executive KPIs with conditional formatting
- Dynamic charts that update with data changes
- AI-generated insights and trend predictions
- Real-time data validation indicators

### Data Sheet
- Structured data with data validation rules
- AI-generated data quality scores
- Automated error checking and correction suggestions
- Version history for each data range

### Analysis Sheet
- Complex calculations with formula auditing
- Scenario analysis and sensitivity testing
- AI-optimized calculation methods
- Performance monitoring and optimization

## AI-Generated Enhancements
### Data Quality Metrics
- **Completeness:** {completeness_score}%
- **Accuracy:** {accuracy_score}%
- **Consistency:** {consistency_score}%
- **Timeliness:** {timeliness_score}%

### Performance Optimizations
- **Calculation Speed:** {calculation_speed}ms
- **File Size:** {file_size_mb}MB
- **Memory Usage:** {memory_usage_mb}MB
- **Compatibility:** Excel 2016+ validated

## Security & Compliance
- **Data Encryption:** Workbook password protection applied
- **Access Control:** User permission levels configured
- **Audit Trail:** Complete modification history maintained
- **Regulatory Compliance:** SOX/GAAP requirements met where applicable

## Usage Instructions
1. Update the Dashboard sheet with your specific KPIs
2. Import data into the Data sheet following the established structure
3. Review AI-generated analysis and insights
4. Generate reports using the automated report sheet
5. Review audit trail before finalizing

## Change Management
| Change | Date | Author | Description | AI Impact Assessment |
|--------|------|--------|-------------|---------------------|
| Initial | {created_date} | {author} | Template creation | ✅ No impact |

---
*Workbook ID: {workbook_id} | AI Validation: ✅ Complete | Last Updated: {timestamp}*
"""
    },
    "sample_word_template": {
        "name": "Word Document Template",
        "category": "document",
        "content": """# Word Document Template - {document_title}
# Version: {version} | Created: {created_date} | Format: DOCX
# AI Enhancement: Content optimization and style consistency applied
# Governance: Track changes enabled | Compliance: Document standards enforced

## Document Properties
- **Title:** {document_title}
- **Author:** {author}
- **Created:** {created_date}
- **Modified:** {modified_date}
- **Version:** {version}
- **Template:** AI-Governed Professional Document

## AI Governance Statement
This Word document has been enhanced by our comprehensive AI governance framework:

- **Content Optimization:** Readability and clarity improvements applied
- **Style Consistency:** Professional formatting standards enforced
- **Compliance Checking:** Regulatory and organizational standards validated
- **Version Control:** Complete change history with diff tracking
- **Collaboration Safety:** Track changes and comments properly configured

## Document Structure
### 1. Executive Summary
[Brief overview of document purpose and key findings]

### 2. Main Content
[Detailed content sections with AI-optimized structure]

### 3. Analysis & Insights
[AI-generated analysis and recommendations]

### 4. Conclusions
[Key takeaways and next steps]

### 5. Appendices
[Supporting data and reference materials]

## AI-Generated Enhancements
### Content Quality Metrics
- **Readability Score:** {readability_score}/100 (Flesch-Kincaid)
- **Clarity Rating:** {clarity_score}/10
- **Structure Optimization:** {structure_score}/10
- **Compliance Score:** {compliance_score}/100

### Style & Formatting
- **Consistency Score:** {consistency_score}/100
- **Professional Standards:** ✅ Met
- **Accessibility Compliance:** WCAG 2.1 AA ✅
- **Brand Guidelines:** ✅ Enforced

## Collaboration Features
- **Track Changes:** Enabled for all edits
- **Comments System:** AI-suggested improvements highlighted
- **Review Workflow:** Structured approval process configured
- **Version History:** Complete document evolution tracked

## Technical Specifications
- **Format:** Office Open XML (DOCX)
- **Compatibility:** Word 2016+ recommended
- **File Size:** Optimized for collaboration
- **Metadata:** Complete document properties included

## Usage Guidelines
1. Replace placeholder content with your specific information
2. Review AI-generated suggestions in comments
3. Use Track Changes for all modifications
4. Follow the established document structure
5. Validate final version against compliance requirements

## Change History
| Version | Date | Modified By | Changes Made | AI Validation |
|---------|------|-------------|--------------|---------------|
| {version} | {created_date} | {author} | Initial creation with AI enhancements | ✅ Passed |

---
*Document ID: {document_id} | AI Enhancement Score: {enhancement_score}/10 | Generated: {timestamp}*
"""
    },
    "sample_powerpoint_template": {
        "name": "PowerPoint Presentation Template",
        "category": "presentation",
        "content": """# PowerPoint Presentation Template - {presentation_title}
# Version: {version} | Created: {created_date} | Format: PPTX
# AI Design: Automated slide layout and content optimization
# Governance: Slide-level change tracking | Compliance: Presentation standards enforced

## Presentation Properties
- **Title:** {presentation_title}
- **Presenter:** {presenter}
- **Created:** {created_date}
- **Modified:** {modified_date}
- **Version:** {version}
- **Theme:** AI-Optimized Professional

## AI Governance Statement
This PowerPoint presentation has been optimized by our AI governance framework:

- **Design Optimization:** Visual hierarchy and layout automatically optimized
- **Content Structuring:** Narrative flow and key messages enhanced
- **Accessibility Compliance:** Screen reader compatibility ensured
- **Performance Optimization:** File size optimized for sharing
- **Brand Consistency:** Organizational design standards enforced

## Slide Structure
### Slide 1: Title Slide
- Presentation title and subtitle
- Presenter name and date
- Organization branding
- AI-generated tagline

### Slide 2: Agenda
- Presentation outline
- Key topics and timing
- AI-optimized flow suggestions

### Content Slides (3-{n})
- Topic introduction
- Key data and insights
- AI-generated visuals and charts
- Supporting evidence and analysis

### Slide {n+1}: Conclusions
- Key takeaways
- Next steps and recommendations
- Q&A prompts

## AI-Generated Enhancements
### Design Quality Metrics
- **Visual Appeal:** {visual_appeal}/10
- **Clarity Score:** {clarity_score}/10
- **Engagement Potential:** {engagement_score}/10
- **Professional Standards:** ✅ Met

### Content Optimization
- **Narrative Flow:** {narrative_flow}/10
- **Key Message Clarity:** {message_clarity}/10
- **Supporting Evidence:** {evidence_strength}/10
- **Call-to-Action Strength:** {cta_strength}/10

## Technical Specifications
- **Format:** Office Open XML (PPTX)
- **Compatibility:** PowerPoint 2016+ recommended
- **Resolution:** 1920x1080 (16:9 aspect ratio)
- **File Size:** Optimized for email/sharing
- **Animation:** Subtle, professional transitions

## Usage Guidelines
1. Review AI-generated slide layouts and content suggestions
2. Customize content while maintaining visual consistency
3. Use presenter notes for additional context
4. Test presentation on target display equipment
5. Validate final version against organizational standards

## Presentation Analytics
| Metric | Score | AI Assessment |
|--------|-------|----------------|
| Engagement Potential | {engagement_score}/10 | {engagement_feedback} |
| Content Clarity | {clarity_score}/10 | {clarity_feedback} |
| Visual Impact | {visual_appeal}/10 | {visual_feedback} |
| Overall Effectiveness | {effectiveness_score}/10 | {effectiveness_feedback} |

## Change History
| Version | Date | Modified By | Changes Made | AI Validation |
|---------|------|-------------|--------------|---------------|
| {version} | {created_date} | {presenter} | Initial creation with AI optimization | ✅ Passed |

---
*Presentation ID: {presentation_id} | AI Design Score: {design_score}/10 | Generated: {timestamp}*
"""
    },
    "sample_docx_template": {
        "name": "Word Document Template",
        "category": "document",
        "content": """# Word Document Template - {document_title}
# Version: {version} | Created: {created_date} | Format: DOCX
# AI Governance: every AI edit is tracked | every change is diffed | every output is accountable
# Version History: every document has a version history | every operation has a timestamp | every action is reversible

## Document Properties
- **Title:** {document_title}
- **Author:** {author}
- **Classification:** {classification}
- **Version:** {version}
- **Last Modified:** {modified_date}

## AI + Office Roles
- OneNote becomes the living structured memory
- Word becomes the formatted deliverable engine
- Excel becomes the analytical substrate
- Git becomes the brain stem holding the lineage of every thought
- ChatGPT becomes the reasoning center
- Daemons become the continuous active cortex
- AIC/Sora/Aria become the interpretive personalities that guide knowledge formation

## Executive Summary
{summary}

## Core Sections
{sections}

## Governance Footnotes
- Track Changes enabled for all contributors
- Automated diffs stored at: {diff_path}
- Version tag recorded at: {version_tag}
- External collaboration handled with: {external_company}

## Change Log
| Version | Timestamp | Author | Notes |
|---------|-----------|--------|-------|
| {version} | {modified_date} | {author} | Initial AI-enhanced draft |

*Document ID: {document_id} | Managed by AI Ops Feed*
"""
    },
    "sample_xlsx_template": {
        "name": "Excel Workbook Template",
        "category": "data",
        "content": """# Excel Workbook Template - {workbook_name}
# Version: {version} | Created: {created_date} | Format: XLSX
# Analytics Fabric: Excel becomes the analytical substrate | alerts the user when something's outdated
# Governance: every AI edit is tracked | every change is diffed | every operation has a timestamp

## Sheets and Purpose
- **Inputs:** capture assumptions and raw data (validated at {created_date})
- **Models:** calculation blocks with automated dependency checks
- **Dashboards:** charts and KPIs refreshed by daemons
- **Audit Trail:** Git-backed snapshots for each AI/analyst touch

## Named Ranges
- assumptions_rate
- revenue_growth
- opex_schedule

## Cell-Level Metadata
- Validation state: {validation_state}
- Last AI touch: {last_ai_edit}
- External system: {external_company}

## AI Observability
- notices missing documents
- drafts proposals
- updates reports
- summarizes notebooks
- analyzes spreadsheets
- reorganizes folders
- updates tasks
- alerts the user when something's outdated
- tracks version history
- suggests improvements
- predicts next steps
- executes workflows

*Workbook ID: {workbook_id} | Diff Path: {diff_path} | Managed by AI Ops Feed*
"""
    },
    "sample_text_template": {
        "name": "Plain Text Document Template",
        "category": "document",
        "content": """# Plain Text Document Template - {document_title}
# Version: {version} | Created: {created_date} | Format: TXT
# AI Processing: Content analysis and optimization completed
# Governance: Line-by-line change tracking | Compliance: Text standards validated

Document Title: {document_title}
Version: {version}
Created: {created_date}
Modified: {modified_date}
Author: {author}

AI GOVERNANCE STATEMENT
======================
This plain text document has been processed by our AI governance framework:

- Content Analysis: Automated readability and clarity assessment completed
- Structure Optimization: Logical flow and organization enhanced
- Compliance Checking: Required standards and formatting validated
- Version Control: Complete change history maintained via Git
- Accessibility: Plain text format ensures universal compatibility

DOCUMENT OVERVIEW
================
{overview}

AI-GENERATED INSIGHTS
====================
Readability Score: {readability_score}/100
Clarity Rating: {clarity_score}/10
Structure Score: {structure_score}/10
Compliance Status: {compliance_status}

MAIN CONTENT
===========
{main_content}

TECHNICAL SPECIFICATIONS
=======================
- Format: UTF-8 encoded plain text
- Line Endings: Unix (LF) standard
- Maximum Line Length: 80 characters recommended
- Encoding: Unicode support for international characters

USAGE GUIDELINES
===============
1. Maintain consistent indentation and formatting
2. Use descriptive headings for content organization
3. Include version information for change tracking
4. Validate content against organizational standards
5. Preserve document structure for automated processing

CHANGE HISTORY
=============
Version {version} - {created_date} - {author}
- Initial creation with AI governance framework
- Content optimization and structure enhancement applied
- Compliance validation completed

AI VALIDATION: ✅ PASSED
Document ID: {document_id}
Generated: {timestamp}
"""
    }
}


def initialize_default_templates(conn: sqlite3.Connection):
    """Initialize default templates in the database."""
    for template_id, template_data in DEFAULT_TEMPLATES.items():
        # Check if template already exists
        c = conn.cursor()
        c.execute("SELECT id FROM document_templates WHERE id = ?", (template_id,))
        if c.fetchone():
            continue  # Skip if already exists
        
        # Insert default template
        created_at = datetime.now().isoformat(timespec="seconds")

        # Extract placeholders from template content
        placeholders = get_template_placeholders(DocumentTemplate(
            id=template_id,
            name=template_data["name"],
            category=template_data["category"],
            content=template_data["content"],
            created_at=created_at
        ))

        # Generate description based on template category and name
        descriptions = {
            "briefs": "Structured brief template with AI governance tracking",
            "proposals": "Comprehensive proposal template with analysis and compliance features",
            "compliance": "Regulatory compliance report template with automated monitoring",
            "meeting": "Meeting documentation template with AI insights and action tracking",
            "reports": "Progress and status report template with predictive analytics",
            "healthcare": "Healthcare documentation template with HIPAA compliance",
            "risk": "Risk assessment template with AI modeling and mitigation strategies",
            "regulatory": "Regulatory filing template with compliance automation",
            "engineering": "Technical specification template with feasibility analysis",
            "technical": "Technical documentation template with accuracy validation",
            "product": "Product update template with adoption prediction and analysis",
            "operations": "Operational manual template with process optimization",
            "data": "Data structure template with governance and validation",
            "document": "General document template with AI enhancement features",
            "presentation": "Presentation template with design optimization"
        }

        description = descriptions.get(template_data["category"], f"{template_data['name']} template with AI governance")

        c.execute("""
            INSERT INTO document_templates (id, name, category, content, description, placeholders, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            template_id,
            template_data["name"],
            template_data["category"],
            template_data["content"],
            description,
            ",".join(placeholders),
            created_at
        ))
    
    conn.commit()


def get_templates(conn: sqlite3.Connection, category: Optional[str] = None) -> List[DocumentTemplate]:
    """Get all templates, optionally filtered by category.
    
    Args:
        conn: Database connection
        category: Optional category filter
    
    Returns:
        List of DocumentTemplate objects
    """
    c = conn.cursor()
    
    if category:
        c.execute("""
            SELECT id, name, category, content, created_at, updated_at
            FROM document_templates
            WHERE category = ?
            ORDER BY name
        """, (category,))
    else:
        c.execute("""
            SELECT id, name, category, content, created_at, updated_at
            FROM document_templates
            ORDER BY category, name
        """)
    
    rows = c.fetchall()
    templates = []
    for row in rows:
        templates.append(DocumentTemplate(
            id=row["id"],
            name=row["name"],
            category=row["category"],
            content=row["content"],
            created_at=row["created_at"],
            updated_at=row.get("updated_at")
        ))
    
    return templates


def get_template(conn: sqlite3.Connection, template_id: str) -> Optional[DocumentTemplate]:
    """Get a specific template by ID."""
    c = conn.cursor()
    c.execute("""
        SELECT id, name, category, content, created_at, updated_at
        FROM document_templates
        WHERE id = ?
    """, (template_id,))
    
    row = c.fetchone()
    if not row:
        return None
    
    return DocumentTemplate(
        id=row["id"],
        name=row["name"],
        category=row["category"],
        content=row["content"],
        created_at=row["created_at"],
        updated_at=row.get("updated_at")
    )


def create_template(
    conn: sqlite3.Connection,
    name: str,
    category: str,
    content: str,
    template_id: Optional[str] = None
) -> str:
    """Create a new template.
    
    Args:
        conn: Database connection
        name: Template name
        category: Template category
        content: Template content with {placeholders}
        template_id: Optional custom ID (auto-generated if not provided)
    
    Returns:
        Template ID
    """
    if template_id is None:
        template_id = str(uuid.uuid4())
    
    created_at = datetime.now().isoformat(timespec="seconds")
    
    c = conn.cursor()
    c.execute("""
        INSERT INTO document_templates (id, name, category, content, created_at)
        VALUES (?, ?, ?, ?, ?)
    """, (template_id, name, category, content, created_at))
    
    conn.commit()
    return template_id


def update_template(
    conn: sqlite3.Connection,
    template_id: str,
    name: Optional[str] = None,
    category: Optional[str] = None,
    content: Optional[str] = None
) -> bool:
    """Update an existing template."""
    updates = []
    params = []
    
    if name is not None:
        updates.append("name = ?")
        params.append(name)
    
    if category is not None:
        updates.append("category = ?")
        params.append(category)
    
    if content is not None:
        updates.append("content = ?")
        params.append(content)
    
    if not updates:
        return False
    
    updated_at = datetime.now().isoformat(timespec="seconds")
    updates.append("updated_at = ?")
    params.append(updated_at)
    params.append(template_id)
    
    c = conn.cursor()
    c.execute(f"""
        UPDATE document_templates
        SET {', '.join(updates)}
        WHERE id = ?
    """, params)
    
    conn.commit()
    return c.rowcount > 0


def delete_template(conn: sqlite3.Connection, template_id: str) -> bool:
    """Delete a template."""
    c = conn.cursor()
    c.execute("DELETE FROM document_templates WHERE id = ?", (template_id,))
    conn.commit()
    return c.rowcount > 0


def render_template(template: DocumentTemplate, values: Dict[str, str]) -> str:
    """Render a template with provided values.
    
    Args:
        template: DocumentTemplate object
        values: Dict mapping placeholder names to values
    
    Returns:
        Rendered document as string
    """
    content = template.content
    
    # Find all placeholders in the template
    placeholders = re.findall(r'\{(\w+)\}', content)
    
    # Replace placeholders with values
    for placeholder in placeholders:
        value = values.get(placeholder, f"{{{{ {placeholder} }}}}")  # Keep placeholder if not found
        content = content.replace(f"{{{placeholder}}}", str(value))
    
    return content


def get_template_placeholders(template: DocumentTemplate) -> List[str]:
    """Extract all placeholder names from a template."""
    placeholders = re.findall(r'\{(\w+)\}', template.content)
    return list(set(placeholders))  # Remove duplicates


def get_categories(conn: sqlite3.Connection) -> List[str]:
    """Get all unique template categories."""
    c = conn.cursor()
    c.execute("SELECT DISTINCT category FROM document_templates ORDER BY category")
    rows = c.fetchall()
    return [row["category"] for row in rows]



