#!/usr/bin/env python3
"""
Codex Spawner - Automatically spawn new codex/AI assistant sessions
based on TODOs and pending tasks.

This script reads TODO files, analyzes them, and spawns new terminal
sessions with appropriate context for AI assistants to work on them.

Usage:
    # Spawn codex for high-priority TODOs
    python scripts/codex_spawner.py --priority high
    
    # Spawn codex for specific project
    python scripts/codex_spawner.py --project my-project
    
    # Dry run to see what would be spawned
    python scripts/codex_spawner.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


@dataclass
class CodexSession:
    """Information about a codex session to spawn."""
    project: str
    todo_file: Path
    todos: List[str]
    priority: str
    context: str
    working_dir: Path


class CodexSpawner:
    """Manages spawning of codex/AI assistant sessions."""
    
    def __init__(
        self,
        *,
        log_dir: Path = REPO_ROOT / "logs",
        terminals_dir: Path = Path.home() / ".cursor" / "projects" / "workspace" / "terminals",
    ):
        self.log_dir = log_dir
        self.terminals_dir = terminals_dir
        
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.terminals_dir.mkdir(parents=True, exist_ok=True)
    
    def read_todos_from_status(self) -> List[CodexSession]:
        """Read TODOs from the status report generated by master orchestrator."""
        status_file = self.log_dir / "status_report.json"
        
        if not status_file.exists():
            print(f"⚠️  Status report not found at {status_file}")
            print("  Hint: Run os_dashboard_ai_assistant.py first to generate it")
            return []
        
        try:
            with status_file.open("r", encoding="utf-8") as f:
                status = json.load(f)
        except Exception as e:
            print(f"❌ Error reading status report: {e}")
            return []
        
        sessions: List[CodexSession] = []
        
        # Read projects and their TODOs
        for project_name, project_info in status.get("projects", {}).items():
            todo_count = project_info.get("todo_count", 0)
            
            if todo_count > 0:
                project_path = Path(project_info["path"])
                
                # Find TODO files in this project
                todo_files = self._find_todo_files(project_path)
                
                for todo_file in todo_files:
                    todos = self._extract_todos_from_file(todo_file)
                    
                    if todos:
                        # Determine priority
                        priority = self._determine_priority(todos)
                        
                        # Build context
                        context = self._build_context(project_path, todo_file, todos)
                        
                        session = CodexSession(
                            project=project_name,
                            todo_file=todo_file,
                            todos=todos,
                            priority=priority,
                            context=context,
                            working_dir=project_path,
                        )
                        sessions.append(session)
        
        return sessions
    
    def _find_todo_files(self, project_path: Path) -> List[Path]:
        """Find TODO files in a project."""
        patterns = [
            "TODO.md", "TODOS.md", "TODO.txt",
            "REMAINING_TODOS.md", "OSD_TODO.md", "FUTURE_TODOS.md",
            ".todo", "todo.json"
        ]
        
        todo_files = []
        for pattern in patterns:
            todo_file = project_path / pattern
            if todo_file.exists():
                todo_files.append(todo_file)
        
        return todo_files
    
    def _extract_todos_from_file(self, todo_file: Path) -> List[str]:
        """Extract TODO items from a file."""
        todos = []
        
        try:
            with todo_file.open("r", encoding="utf-8") as f:
                lines = f.readlines()
            
            for line in lines:
                line = line.strip()
                
                # Match TODO patterns
                if any(marker in line.lower() for marker in ["- [ ]", "todo:", "fixme:", "hack:"]):
                    # Skip completed items
                    if "- [x]" in line.lower() or "✓" in line or "✅" in line:
                        continue
                    
                    todos.append(line)
        
        except Exception as e:
            print(f"⚠️  Error reading {todo_file}: {e}")
        
        return todos
    
    def _determine_priority(self, todos: List[str]) -> str:
        """Determine priority based on TODO content."""
        content = " ".join(todos).lower()
        
        if any(word in content for word in ["critical", "urgent", "asap", "blocker"]):
            return "critical"
        elif any(word in content for word in ["important", "high", "soon"]):
            return "high"
        elif any(word in content for word in ["low", "someday", "maybe", "nice to have"]):
            return "low"
        else:
            return "normal"
    
    def _build_context(self, project_path: Path, todo_file: Path, todos: List[str]) -> str:
        """Build context string for codex."""
        lines = [
            "=" * 80,
            f"PROJECT: {project_path.name}",
            f"TODO FILE: {todo_file.name}",
            f"WORKING DIR: {project_path}",
            "=" * 80,
            "",
            "PENDING TASKS:",
            "",
        ]
        
        for i, todo in enumerate(todos, 1):
            lines.append(f"{i}. {todo}")
        
        lines.extend([
            "",
            "=" * 80,
            "INSTRUCTIONS FOR AI ASSISTANT:",
            "=" * 80,
            "",
            "You are an autonomous AI assistant working on the tasks listed above.",
            "Your role is to:",
            "",
            "1. Analyze each TODO item and understand the requirements",
            "2. Break down complex tasks into smaller, actionable steps",
            "3. Implement the required changes systematically",
            "4. Test your changes to ensure they work correctly",
            "5. Mark items as complete when finished",
            "",
            "Available tools:",
            "- Full access to the codebase and all files",
            "- Ability to read, write, and modify files",
            "- Ability to run commands and tests",
            "- Access to git for version control",
            "",
            "Best practices:",
            "- Read existing code to understand patterns and conventions",
            "- Make incremental changes and test frequently",
            "- Follow existing code style and architecture",
            "- Document your changes with clear comments",
            "- Update tests when adding new features",
            "",
            "Get started by analyzing the first TODO item and creating a plan.",
            "",
        ])
        
        return "\n".join(lines)
    
    def spawn_codex_session(self, session: CodexSession, dry_run: bool = False) -> bool:
        """Spawn a new codex/AI assistant session."""
        print(f"🚀 Spawning codex session for: {session.project}")
        print(f"   Priority: {session.priority}")
        print(f"   TODOs: {len(session.todos)}")
        print(f"   Working dir: {session.working_dir}")
        
        if dry_run:
            print("   [DRY RUN] Would spawn session with context:")
            print("")
            print(session.context)
            print("")
            return True
        
        # Create a context file for the session
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        context_file = self.terminals_dir / f"codex_{session.project}_{timestamp}.txt"
        
        with context_file.open("w", encoding="utf-8") as f:
            f.write(session.context)
        
        print(f"   ✓ Context saved to: {context_file}")
        
        # Prepare the command to launch a new terminal
        # This will depend on the terminal emulator being used
        
        # For macOS Terminal
        if sys.platform == "darwin":
            applescript = f'''
            tell application "Terminal"
                activate
                do script "cd {session.working_dir} && cat {context_file} && echo '' && echo 'Ready to work on TODOs. Type your commands or ask questions.'"
            end tell
            '''
            
            try:
                subprocess.run(
                    ["osascript", "-e", applescript],
                    check=True,
                    capture_output=True,
                )
                print(f"   ✓ Terminal session launched!")
                return True
            except Exception as e:
                print(f"   ❌ Failed to launch terminal: {e}")
                return False
        
        # For Linux with gnome-terminal
        elif sys.platform == "linux":
            try:
                subprocess.Popen(
                    [
                        "gnome-terminal",
                        "--",
                        "bash",
                        "-c",
                        f"cd {session.working_dir} && cat {context_file} && echo '' && echo 'Ready to work on TODOs.' && bash",
                    ],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                print(f"   ✓ Terminal session launched!")
                return True
            except Exception as e:
                print(f"   ❌ Failed to launch terminal: {e}")
                print(f"   Hint: Install gnome-terminal or modify script for your terminal emulator")
                return False
        
        # For Windows
        elif sys.platform == "win32":
            try:
                # Try Windows Terminal first
                subprocess.Popen(
                    [
                        "wt.exe",
                        "-d", str(session.working_dir),
                        "cmd", "/k", f"type {context_file}",
                    ],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                print(f"   ✓ Terminal session launched!")
                return True
            except Exception:
                # Fall back to cmd.exe
                try:
                    subprocess.Popen(
                        [
                            "cmd.exe",
                            "/c", "start", "cmd.exe",
                            "/k", f"cd /d {session.working_dir} && type {context_file}",
                        ],
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                    print(f"   ✓ Terminal session launched!")
                    return True
                except Exception as e:
                    print(f"   ❌ Failed to launch terminal: {e}")
                    return False
        
        else:
            print(f"   ⚠️  Unsupported platform: {sys.platform}")
            print(f"   Context file created at: {context_file}")
            print(f"   Please open a terminal manually and run: cd {session.working_dir} && cat {context_file}")
            return False
    
    def spawn_sessions(
        self,
        *,
        priority_filter: Optional[str] = None,
        project_filter: Optional[str] = None,
        max_sessions: int = 0,
        dry_run: bool = False,
    ) -> int:
        """Spawn codex sessions based on filters."""
        print("🔍 Reading TODO status...")
        sessions = self.read_todos_from_status()
        
        if not sessions:
            print("✅ No pending TODOs found!")
            return 0
        
        print(f"📋 Found {len(sessions)} projects with TODOs")
        
        # Apply filters
        filtered_sessions = []
        for session in sessions:
            if priority_filter and session.priority != priority_filter:
                continue
            if project_filter and project_filter not in session.project:
                continue
            filtered_sessions.append(session)
        
        if not filtered_sessions:
            print(f"⚠️  No sessions match the filter criteria")
            return 0
        
        # Apply max sessions limit
        if max_sessions > 0:
            filtered_sessions = filtered_sessions[:max_sessions]
        
        print(f"🚀 Spawning {len(filtered_sessions)} codex session(s)...")
        print("")
        
        success_count = 0
        for session in filtered_sessions:
            if self.spawn_codex_session(session, dry_run=dry_run):
                success_count += 1
            print("")
        
        print("=" * 80)
        print(f"✅ Spawned {success_count}/{len(filtered_sessions)} sessions successfully")
        print("=" * 80)
        
        return success_count


def main():
    parser = argparse.ArgumentParser(
        description="Spawn codex/AI assistant sessions for pending TODOs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Spawn for all high-priority TODOs
    python scripts/codex_spawner.py --priority high
    
    # Spawn for specific project
    python scripts/codex_spawner.py --project my-project
    
    # Dry run to preview
    python scripts/codex_spawner.py --dry-run
    
    # Spawn one session at a time
    python scripts/codex_spawner.py --max-sessions 1
        """
    )
    
    parser.add_argument(
        "--priority",
        choices=["low", "normal", "high", "critical"],
        help="Only spawn sessions for TODOs with this priority",
    )
    
    parser.add_argument(
        "--project",
        help="Only spawn sessions for projects matching this name",
    )
    
    parser.add_argument(
        "--max-sessions",
        type=int,
        default=0,
        help="Maximum number of sessions to spawn (0 = unlimited)",
    )
    
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without actually spawning sessions",
    )
    
    parser.add_argument(
        "--log-dir",
        type=Path,
        default=REPO_ROOT / "logs",
        help="Directory containing status reports",
    )
    
    args = parser.parse_args()
    
    spawner = CodexSpawner(log_dir=args.log_dir)
    
    success_count = spawner.spawn_sessions(
        priority_filter=args.priority,
        project_filter=args.project,
        max_sessions=args.max_sessions,
        dry_run=args.dry_run,
    )
    
    return 0 if success_count > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
