#!/usr/bin/env python3
"""Codex Continuation Daemon - Automatic TODO handoff between AI sessions.

This daemon watches for continuation payloads generated by the unified
orchestrator and triggers new AI/Codex sessions to continue work on
remaining TODOs, failed tests, and outstanding issues.

Per Technical Spec V6:
- Section 4.3: Daemon Families & Roles
- Section 8.23: Self-Evolving Capsule Ecosystem
- Section 17.4.3: Self-Evolving Capsule Ecosystem

The daemon implements the "Autonomous Research Conductor" pattern where
AI sessions can hand off work to subsequent sessions automatically.

Examples:
    # Watch for continuation files and process them
    python scripts/codex_continuation_daemon.py --watch

    # Process a specific continuation file
    python scripts/codex_continuation_daemon.py --process .osdash-continuation.json

    # Generate a prompt for manual codex invocation
    python scripts/codex_continuation_daemon.py --generate-prompt .osdash-continuation.json

    # Run once and exit (for CI/cron usage)
    python scripts/codex_continuation_daemon.py --once
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTINUATION_FILE = ".osdash-continuation.json"
DAEMON_STATE_FILE = ".osdash-daemon-state.json"
PROMPT_OUTPUT_FILE = ".osdash-next-prompt.md"

# Supported AI/Codex invocation methods
CODEX_METHODS = ["cursor", "vscode", "terminal", "api", "manual"]


@dataclass
class ContinuationPayload:
    """Parsed continuation payload from orchestrator."""
    timestamp: str
    workspace_root: str
    continuation_required: bool
    priority_todos: List[Dict[str, Any]]
    failed_projects: List[Dict[str, Any]]
    recommended_actions: List[Dict[str, Any]]
    context_for_next_session: str
    
    @classmethod
    def from_file(cls, path: Path) -> Optional["ContinuationPayload"]:
        """Load payload from a JSON file."""
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            return cls(
                timestamp=data.get("timestamp", ""),
                workspace_root=data.get("workspace_root", ""),
                continuation_required=data.get("continuation_required", False),
                priority_todos=data.get("priority_todos", []),
                failed_projects=data.get("failed_projects", []),
                recommended_actions=data.get("recommended_actions", []),
                context_for_next_session=data.get("context_for_next_session", ""),
            )
        except Exception:
            return None
    
    def to_prompt(self) -> str:
        """Generate a comprehensive prompt for the next AI session."""
        sections = []
        
        # Header
        sections.append("# Continuation Session - Automated TODO Handoff")
        sections.append(f"\n**Generated:** {datetime.now(timezone.utc).isoformat()}")
        sections.append(f"**Previous Session:** {self.timestamp}")
        sections.append(f"**Workspace:** {self.workspace_root}")
        
        # Context from previous session
        if self.context_for_next_session:
            sections.append("\n## Previous Session Context")
            sections.append(self.context_for_next_session)
        
        # Priority TODOs
        if self.priority_todos:
            sections.append("\n## Priority TODOs to Address")
            sections.append("These items were marked as critical/high priority and need attention:\n")
            for i, todo in enumerate(self.priority_todos[:15], 1):
                priority = todo.get("priority", "normal").upper()
                content = todo.get("content", "Unknown")
                source = todo.get("source_file", "unknown")
                category = todo.get("category", "general")
                sections.append(f"{i}. **[{priority}]** [{category}] {content}")
                sections.append(f"   - Source: `{source}`")
        
        # Failed projects
        if self.failed_projects:
            sections.append("\n## Projects Needing Repair")
            sections.append("These projects had failing tests or auto-fix issues:\n")
            for project in self.failed_projects:
                name = project.get("name", "Unknown")
                path = project.get("path", "")
                autofix = project.get("autofix_status", "unknown")
                test = project.get("test_status", "unknown")
                errors = project.get("errors", [])
                
                sections.append(f"### {name}")
                sections.append(f"- **Path:** `{path}`")
                sections.append(f"- **Auto-fix Status:** {autofix}")
                sections.append(f"- **Test Status:** {test}")
                if errors:
                    sections.append(f"- **Errors:**")
                    for err in errors[:3]:
                        sections.append(f"  - {err[:200]}")
        
        # Recommended actions
        if self.recommended_actions:
            sections.append("\n## Recommended Actions")
            for action in self.recommended_actions:
                desc = action.get("description", "")
                items = action.get("items", [])
                projects = action.get("projects", [])
                
                sections.append(f"\n### {desc}")
                if items:
                    for item in items[:5]:
                        sections.append(f"- {item}")
                if projects:
                    sections.append(f"- Projects: {', '.join(projects)}")
        
        # Instructions for AI
        sections.append("\n## Instructions")
        sections.append("""
1. Review the priority TODOs above and address them in order of priority
2. For failed projects, investigate the errors and apply fixes
3. Run tests after making changes to verify fixes
4. If new issues are discovered, add them to the appropriate TODO files
5. Generate a new continuation payload if work remains incomplete
6. Use the unified_project_orchestrator to scan for additional issues

**Key Commands:**
```bash
# Scan workspace for issues
python scripts/unified_project_orchestrator.py --root . --execute

# Run auto-fix on specific project
python scripts/ai_auto_fix.py --logs-only

# Run workspace auto-guard
python scripts/workspace_auto_guard.py --root . --execute
```
""")
        
        return "\n".join(sections)
    
    def to_compact_prompt(self) -> str:
        """Generate a compact prompt suitable for API calls."""
        lines = [
            "Continue work on OS Dashboard AI Assistant project.",
            "",
            "Priority items:",
        ]
        
        for todo in self.priority_todos[:5]:
            lines.append(f"- {todo.get('content', 'Unknown')}")
        
        if self.failed_projects:
            lines.append("\nFix these projects:")
            for p in self.failed_projects[:3]:
                lines.append(f"- {p.get('name')}: {p.get('errors', ['unknown'])[0][:100]}")
        
        lines.append("\nRun: python scripts/unified_project_orchestrator.py --execute")
        
        return "\n".join(lines)


@dataclass
class DaemonState:
    """Persistent state for the continuation daemon."""
    last_processed: Optional[str] = None
    processed_count: int = 0
    last_payload_hash: Optional[str] = None
    sessions_triggered: int = 0
    errors: List[str] = field(default_factory=list)
    
    @classmethod
    def load(cls, path: Path) -> "DaemonState":
        """Load state from file."""
        try:
            if path.exists():
                data = json.loads(path.read_text())
                return cls(
                    last_processed=data.get("last_processed"),
                    processed_count=data.get("processed_count", 0),
                    last_payload_hash=data.get("last_payload_hash"),
                    sessions_triggered=data.get("sessions_triggered", 0),
                    errors=data.get("errors", []),
                )
        except Exception:
            pass
        return cls()
    
    def save(self, path: Path) -> None:
        """Save state to file."""
        path.write_text(json.dumps({
            "last_processed": self.last_processed,
            "processed_count": self.processed_count,
            "last_payload_hash": self.last_payload_hash,
            "sessions_triggered": self.sessions_triggered,
            "errors": self.errors[-10:],  # Keep last 10 errors
        }, indent=2))


class ContinuationDaemon:
    """Daemon that watches for continuation payloads and triggers AI sessions."""
    
    def __init__(
        self,
        workspace: Path,
        method: str = "manual",
        poll_interval: float = 30.0,
        auto_trigger: bool = False,
        verbose: bool = True,
    ):
        self.workspace = workspace.expanduser().resolve()
        self.method = method
        self.poll_interval = poll_interval
        self.auto_trigger = auto_trigger
        self.verbose = verbose
        
        self.continuation_file = self.workspace / CONTINUATION_FILE
        self.state_file = self.workspace / DAEMON_STATE_FILE
        self.prompt_file = self.workspace / PROMPT_OUTPUT_FILE
        
        self.state = DaemonState.load(self.state_file)
        self._stop_event = threading.Event()
    
    def watch(self) -> None:
        """Watch for continuation files continuously."""
        self._log("🔄 Starting continuation daemon...")
        self._log(f"   Watching: {self.continuation_file}")
        self._log(f"   Method: {self.method}")
        self._log(f"   Poll interval: {self.poll_interval}s")
        
        # Set up signal handlers
        signal.signal(signal.SIGINT, self._signal_handler)
        signal.signal(signal.SIGTERM, self._signal_handler)
        
        while not self._stop_event.is_set():
            try:
                self._check_and_process()
            except Exception as e:
                self._log(f"❌ Error during check: {e}")
                self.state.errors.append(f"{datetime.now(timezone.utc).isoformat()}: {e}")
                self.state.save(self.state_file)
            
            self._stop_event.wait(self.poll_interval)
        
        self._log("⏹️  Daemon stopped")
    
    def process_once(self) -> bool:
        """Process continuation file once and exit."""
        return self._check_and_process()
    
    def _check_and_process(self) -> bool:
        """Check for continuation file and process if found."""
        if not self.continuation_file.exists():
            return False
        
        # Load payload
        payload = ContinuationPayload.from_file(self.continuation_file)
        if not payload:
            self._log("⚠️  Could not parse continuation file")
            return False
        
        if not payload.continuation_required:
            self._log("ℹ️  No continuation required")
            return False
        
        # Check if already processed (by comparing hash)
        import hashlib
        content = self.continuation_file.read_text()
        current_hash = hashlib.md5(content.encode()).hexdigest()
        
        if current_hash == self.state.last_payload_hash:
            # Already processed this exact payload
            return False
        
        self._log(f"📋 Found continuation payload from {payload.timestamp}")
        self._log(f"   Priority TODOs: {len(payload.priority_todos)}")
        self._log(f"   Failed projects: {len(payload.failed_projects)}")
        
        # Generate prompt
        prompt = payload.to_prompt()
        self.prompt_file.write_text(prompt, encoding="utf-8")
        self._log(f"📝 Prompt written to: {self.prompt_file}")
        
        # Trigger continuation based on method
        triggered = self._trigger_continuation(payload, prompt)
        
        # Update state
        self.state.last_processed = datetime.now(timezone.utc).isoformat()
        self.state.processed_count += 1
        self.state.last_payload_hash = current_hash
        if triggered:
            self.state.sessions_triggered += 1
        self.state.save(self.state_file)
        
        return triggered
    
    def _trigger_continuation(self, payload: ContinuationPayload, prompt: str) -> bool:
        """Trigger a new AI session based on configured method."""
        if self.method == "manual":
            self._log("\n" + "="*60)
            self._log("MANUAL CONTINUATION REQUIRED")
            self._log("="*60)
            self._log(f"Prompt saved to: {self.prompt_file}")
            self._log("\nTo continue, either:")
            self._log("1. Open the prompt file and paste into your AI assistant")
            self._log("2. Run: cursor --open-file .osdash-next-prompt.md")
            self._log("3. Use the VS Code Copilot extension")
            self._log("="*60 + "\n")
            return False
        
        elif self.method == "cursor":
            return self._trigger_cursor(prompt)
        
        elif self.method == "vscode":
            return self._trigger_vscode(prompt)
        
        elif self.method == "terminal":
            return self._trigger_terminal(payload)
        
        elif self.method == "api":
            return self._trigger_api(payload)
        
        return False
    
    def _trigger_cursor(self, prompt: str) -> bool:
        """Trigger Cursor AI with the continuation prompt."""
        try:
            # Write prompt to file that Cursor can read
            self.prompt_file.write_text(prompt, encoding="utf-8")
            
            # Try to open Cursor with the prompt file
            result = subprocess.run(
                ["cursor", "--open-file", str(self.prompt_file)],
                capture_output=True,
                timeout=10,
            )
            
            if result.returncode == 0:
                self._log("✅ Opened prompt in Cursor")
                return True
            else:
                self._log("⚠️  Could not open Cursor, prompt saved to file")
                return False
                
        except FileNotFoundError:
            self._log("⚠️  Cursor CLI not found, prompt saved to file")
            return False
        except Exception as e:
            self._log(f"❌ Failed to trigger Cursor: {e}")
            return False
    
    def _trigger_vscode(self, prompt: str) -> bool:
        """Trigger VS Code with the continuation prompt."""
        try:
            self.prompt_file.write_text(prompt, encoding="utf-8")
            
            result = subprocess.run(
                ["code", str(self.prompt_file)],
                capture_output=True,
                timeout=10,
            )
            
            if result.returncode == 0:
                self._log("✅ Opened prompt in VS Code")
                return True
            else:
                self._log("⚠️  Could not open VS Code, prompt saved to file")
                return False
                
        except FileNotFoundError:
            self._log("⚠️  VS Code CLI not found, prompt saved to file")
            return False
        except Exception as e:
            self._log(f"❌ Failed to trigger VS Code: {e}")
            return False
    
    def _trigger_terminal(self, payload: ContinuationPayload) -> bool:
        """Launch a new terminal with the orchestrator."""
        try:
            # Create a shell script to run
            script_content = f"""#!/bin/bash
echo "=== OS Dashboard Continuation Session ==="
echo "Triggered: $(date)"
echo ""
cd "{self.workspace}"
python scripts/unified_project_orchestrator.py --root . --execute --continue-todos
echo ""
echo "Session complete. Press any key to close."
read -n 1
"""
            script_file = self.workspace / ".osdash-continue.sh"
            script_file.write_text(script_content)
            script_file.chmod(0o755)
            
            # Try different terminal emulators
            terminals = [
                ["gnome-terminal", "--", "bash", str(script_file)],
                ["xterm", "-e", str(script_file)],
                ["konsole", "-e", str(script_file)],
                ["open", "-a", "Terminal", str(script_file)],  # macOS
            ]
            
            for term_cmd in terminals:
                try:
                    result = subprocess.Popen(
                        term_cmd,
                        start_new_session=True,
                    )
                    self._log(f"✅ Launched continuation in new terminal")
                    return True
                except FileNotFoundError:
                    continue
            
            self._log("⚠️  No terminal emulator found")
            return False
            
        except Exception as e:
            self._log(f"❌ Failed to launch terminal: {e}")
            return False
    
    def _trigger_api(self, payload: ContinuationPayload) -> bool:
        """Trigger continuation via API call to AI service."""
        try:
            # Try to use the project's AI service
            sys.path.insert(0, str(self.workspace))
            
            from assistant_core.ai import generate_ai_reply, openai_available
            
            if not openai_available():
                self._log("⚠️  OpenAI not available for API trigger")
                return False
            
            compact_prompt = payload.to_compact_prompt()
            
            # Create a message for the AI
            from assistant_core.db import ChatMessage
            
            message = ChatMessage(
                id=1,
                persona="AIC",
                role="user",
                kind="chat",
                content=compact_prompt,
            )
            
            reply, error, _ = generate_ai_reply(
                [message],
                persona="AIC",
                append_prompt=False,
                temperature=0.3,
                max_tokens=2000,
            )
            
            if error:
                self._log(f"❌ AI API error: {error}")
                return False
            
            if reply:
                # Save the AI's response
                response_file = self.workspace / ".osdash-ai-response.md"
                response_file.write_text(f"# AI Response\n\n{reply}")
                self._log(f"✅ AI response saved to: {response_file}")
                return True
            
            return False
            
        except ImportError as e:
            self._log(f"⚠️  Could not import AI module: {e}")
            return False
        except Exception as e:
            self._log(f"❌ API trigger failed: {e}")
            return False
    
    def _signal_handler(self, signum, frame):
        """Handle shutdown signals."""
        self._log(f"\n📛 Received signal {signum}, shutting down...")
        self._stop_event.set()
    
    def _log(self, message: str) -> None:
        """Print a log message if verbose."""
        if self.verbose:
            timestamp = datetime.now(timezone.utc).strftime("%H:%M:%S")
            print(f"[{timestamp}] {message}")


def generate_prompt_only(continuation_file: Path, output_file: Optional[Path] = None) -> str:
    """Generate a prompt from a continuation file without triggering anything."""
    payload = ContinuationPayload.from_file(continuation_file)
    if not payload:
        print(f"❌ Could not parse: {continuation_file}")
        return ""
    
    prompt = payload.to_prompt()
    
    if output_file:
        output_file.write_text(prompt, encoding="utf-8")
        print(f"✅ Prompt written to: {output_file}")
    
    return prompt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Codex Continuation Daemon - Automatic TODO handoff",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    
    parser.add_argument(
        "--workspace",
        type=Path,
        default=REPO_ROOT,
        help="Workspace root directory",
    )
    parser.add_argument(
        "--watch",
        action="store_true",
        help="Watch continuously for continuation files",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Process once and exit",
    )
    parser.add_argument(
        "--process",
        type=Path,
        metavar="FILE",
        help="Process a specific continuation file",
    )
    parser.add_argument(
        "--generate-prompt",
        type=Path,
        metavar="FILE",
        help="Generate prompt from continuation file without triggering",
    )
    parser.add_argument(
        "--method",
        choices=CODEX_METHODS,
        default="manual",
        help="How to trigger the next AI session",
    )
    parser.add_argument(
        "--poll-interval",
        type=float,
        default=30.0,
        help="Seconds between checks in watch mode",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output file for generated prompt",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress verbose output",
    )
    
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    
    # Generate prompt only mode
    if args.generate_prompt:
        prompt = generate_prompt_only(
            args.generate_prompt,
            args.output or (args.workspace / PROMPT_OUTPUT_FILE),
        )
        if not args.quiet:
            print(prompt)
        return 0 if prompt else 1
    
    # Process specific file
    if args.process:
        daemon = ContinuationDaemon(
            workspace=args.workspace,
            method=args.method,
            verbose=not args.quiet,
        )
        daemon.continuation_file = args.process.expanduser().resolve()
        return 0 if daemon.process_once() else 1
    
    # Create daemon
    daemon = ContinuationDaemon(
        workspace=args.workspace,
        method=args.method,
        poll_interval=args.poll_interval,
        verbose=not args.quiet,
    )
    
    # Watch mode
    if args.watch:
        daemon.watch()
        return 0
    
    # Once mode (default)
    if args.once or True:  # Default to once if no mode specified
        return 0 if daemon.process_once() else 1


if __name__ == "__main__":
    raise SystemExit(main())
