apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: osdash-secrets
  namespace: osdash-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: osdash-secrets-store
    kind: ClusterSecretStore
  target:
    name: osdash-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: osdash/staging/openai_api_key
    - secretKey: SENTRY_DSN
      remoteRef:
        key: osdash/staging/sentry_dsn
