"""Excel service orchestrating local/cloud operations with AI."""

from __future__ import annotations

import pandas as pd
from typing import Dict, List

from ...ai_layer.tools import excel_generate_pandas_code
from ...versioning import enqueue_commit, enqueue_git_commit
from .cloud_client import ExcelCloudClient, CloudExcelClient
from .local_client import load_sheet, save_sheet, LocalWorkbook


class ExcelService:
    """Provide higher-level Excel actions for the assistant hub."""

    def __init__(self, cloud: ExcelCloudClient | None = None):
        self.cloud = cloud or ExcelCloudClient()

    def summarize_sheet(self, workbook_path: str, sheet_name: str, instruction: str, actor: str = "AIC") -> List[str]:
        df = load_sheet(workbook_path, sheet_name)
        code = excel_generate_pandas_code(df.head(20).to_markdown(index=False), instruction)
        local_vars: dict = {"df": df.copy()}
        try:
            exec(code, {}, local_vars)  # noqa: S102
        except Exception as exc:
            raise RuntimeError(f"Generated pandas code failed: {exc}\nCode:\n{code}") from exc
        
        result_df = local_vars.get("result_df")
        if not isinstance(result_df, pd.DataFrame):
            raise RuntimeError("Generated code did not produce result_df DataFrame")
        
        save_sheet(workbook_path, "Summary", result_df)
        # Auto-commit the changes
        enqueue_commit([workbook_path], actor=actor, tag="excel", reason=f"Summarize sheet {sheet_name}")
        return [workbook_path]


# Backwards compatibility functions
def summarize_local_workbook(path: str, instruction: str, *, actor: str = "AIC") -> Dict[str, str]:
    """Store a text summary alongside a local workbook and auto-commit it."""
    workbook = LocalWorkbook(path)
    summary_text = f"Summary generated by {actor}\nInstruction: {instruction}\nWorkbook: {workbook.path.name}"
    summary_path = workbook.write_summary(instruction, summary_text)
    enqueue_git_commit([summary_path], actor=actor, reason="Excel summary", tag="excel")
    return {"workbook": str(workbook.path), "summary_path": str(summary_path)}


def export_cloud_range_to_csv(
    client: CloudExcelClient | ExcelCloudClient,
    drive_item_id: str,
    worksheet_id: str,
    address: str,
    *,
    actor: str = "AIC",
) -> Dict[str, str]:
    """Fetch a range via Graph and persist it as CSV alongside its workbook mirror."""
    range_data = client.get_range(drive_item_id, worksheet_id, address)
    values: List[List[str]] = range_data.get("values", [])
    filename = f"{drive_item_id}_{worksheet_id}_{address}.csv"
    export_path = LocalWorkbook(filename).export_table("range", values)
    enqueue_git_commit([export_path], actor=actor, reason="Export Excel range", tag="excel")
    return {"export_path": str(export_path), "rows": str(len(values))}
