apiVersion: v1
kind: Service
metadata:
  name: osdash-backend
  labels:
    app: osdash
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: osdash
    component: backend
