"""High-level Excel workflows used by the dashboard."""
from __future__ import annotations

from typing import Dict, List

from assistant_hub.versioning import enqueue_git_commit

from .cloud_client import CloudExcelClient
from .local_client import LocalWorkbook


def summarize_local_workbook(path: str, instruction: str, *, actor: str = "AIC") -> Dict[str, str]:
    """Store a text summary alongside a local workbook and auto-commit it."""
    workbook = LocalWorkbook(path)
    summary_text = f"Summary generated by {actor}\nInstruction: {instruction}\nWorkbook: {workbook.path.name}"
    summary_path = workbook.write_summary(instruction, summary_text)
    enqueue_git_commit([summary_path], actor=actor, reason="Excel summary", tag="excel")
    return {"workbook": str(workbook.path), "summary_path": str(summary_path)}


def export_cloud_range_to_csv(
    client: CloudExcelClient,
    drive_item_id: str,
    worksheet_id: str,
    address: str,
    *,
    actor: str = "AIC",
) -> Dict[str, str]:
    """Fetch a range via Graph and persist it as CSV alongside its workbook mirror."""
    range_data = client.get_range(drive_item_id, worksheet_id, address)
    values: List[List[str]] = range_data.get("values", [])
    filename = f"{drive_item_id}_{worksheet_id}_{address}.csv"
    export_path = LocalWorkbook(filename).export_table("range", values)
    enqueue_git_commit([export_path], actor=actor, reason="Export Excel range", tag="excel")
    return {"export_path": str(export_path), "rows": str(len(values))}
